/**
 * Engineering Content & System Topology
 * Governed strictly by RULES.md Rule 2 (Zero-Invention Policy)
 * 
 * Verified from real GitHub production repositories:
 * Glint, Pitchery, PixelSpace, Fanout, Syncflow
 */
import type { TechSubsystem } from "./types";

export const engineeringSubsystems: TechSubsystem[] = [
  {
    number: "01",
    label: "Frontend",
    title: "Interface Systems",
    description: "Reactive components, server rendering, and micro-interactions.",
    items: [
      {
        id: "react",
        name: "React 19",
        glyph: "⬡",
        category: "Frontend",
        role: "Component architecture, Server Components, and concurrent rendering.",
        connectedIds: ["nextjs", "typescript", "nodejs", "css-modules"],
        project: { title: "Pitchery", slug: "pitchery" },
        specs: ["React 19 Actions", "Concurrent Mode", "Optimistic UI"],
      },
      {
        id: "nextjs",
        name: "Next.js 15",
        glyph: "▲",
        category: "Frontend",
        role: "App Router, streaming SSR, Server Actions, and edge routing.",
        connectedIds: ["react", "typescript", "postgresql", "drizzle", "vercel"],
        project: { title: "Pitchery", slug: "pitchery" },
        specs: ["App Router", "Streaming SSR", "Zero-Waterfall Fetches"],
      },
      {
        id: "typescript",
        name: "TypeScript",
        glyph: "TS",
        category: "Frontend",
        role: "End-to-end type safety, generic constraints, and strict schema validation.",
        connectedIds: ["react", "nextjs", "nodejs", "prisma", "drizzle"],
        project: { title: "Glint", slug: "glint" },
        specs: ["Strict Mode", "Shared Contracts", "Zod Inferred Types"],
      },
      {
        id: "css-modules",
        name: "CSS Modules",
        glyph: "◈",
        category: "Frontend",
        role: "Scoped modular styling, zero runtime overhead, and custom design tokens.",
        connectedIds: ["react", "nextjs"],
        project: { title: "Portfolio", slug: "glint" },
        specs: ["Zero-Runtime", "CSS Variables", "BEM Conventions"],
      },
      {
        id: "tailwind",
        name: "Tailwind CSS",
        glyph: "✦",
        category: "Frontend",
        role: "Utility-first design systems and rapid layout prototyping.",
        connectedIds: ["react", "nextjs"],
        project: { title: "Pitchery", slug: "pitchery" },
        specs: ["Just-In-Time Compiler", "Fluid Typography", "Responsive Breakpoints"],
      },
    ],
  },
  {
    number: "02",
    label: "Backend",
    title: "Core Data & APIs",
    description: "Type-safe schemas, relational storage, and resilient API endpoints.",
    items: [
      {
        id: "nodejs",
        name: "Node.js",
        glyph: "⚡",
        category: "Backend",
        role: "Asynchronous I/O runtime, background workers, and RESTful routing.",
        connectedIds: ["typescript", "postgresql", "prisma", "docker"],
        project: { title: "Fanout", slug: "fanout" },
        specs: ["Event Loop Async", "Streams & WebSockets", "Worker Threads"],
      },
      {
        id: "rest-apis",
        name: "REST APIs",
        glyph: "⇄",
        category: "Backend",
        role: "Contract-driven endpoint design, idempotency, and status code standards.",
        connectedIds: ["nodejs", "typescript", "nextjs"],
        project: { title: "Pitchery", slug: "pitchery" },
        specs: ["RESTful Standards", "Bearer Auth", "Rate Limiting"],
      },
      {
        id: "postgresql",
        name: "PostgreSQL",
        glyph: "⛁",
        category: "Backend",
        role: "Relational persistence, ACID transactions, indexing, and connection pooling.",
        connectedIds: ["prisma", "drizzle", "nodejs", "nextjs"],
        project: { title: "Pitchery", slug: "pitchery" },
        specs: ["ACID Compliance", "B-Tree Indexes", "Connection Pooling"],
      },
      {
        id: "prisma",
        name: "Prisma",
        glyph: "▲",
        category: "Backend",
        role: "Type-safe ORM schema generation, migration tracking, and relational queries.",
        connectedIds: ["postgresql", "typescript", "nodejs"],
        project: { title: "Syncflow", slug: "syncflow" },
        specs: ["Generated Type Safety", "Declarative Migrations", "Relation Querying"],
      },
      {
        id: "drizzle",
        name: "Drizzle ORM",
        glyph: "◇",
        category: "Backend",
        role: "Lightweight, zero-overhead TypeScript SQL query builder and schema management.",
        connectedIds: ["postgresql", "typescript", "nextjs"],
        project: { title: "Pitchery", slug: "pitchery" },
        specs: ["Serverless Ready", "Zero Query Overhead", "Pure SQL Expressions"],
      },
      {
        id: "laravel",
        name: "Laravel",
        glyph: "❖",
        category: "Backend",
        role: "Modular MVC backend architecture, Eloquent ORM relationships, and RESTful routing.",
        connectedIds: ["rest-apis", "postgresql", "react"],
        project: { title: "Freelance", slug: "pitchery" },
        specs: ["Eloquent ORM", "MVC Architecture", "Artisan CLI", "REST Endpoints"],
      },
      {
        id: "django",
        name: "Django",
        glyph: "✦",
        category: "Backend",
        role: "Batteries-included Python backend framework, relational data modeling, and secure API layers.",
        connectedIds: ["rest-apis", "postgresql", "docker"],
        project: { title: "Freelance", slug: "pitchery" },
        specs: ["Django ORM", "Python Backend", "Admin & Auth", "REST Framework"],
      },
    ],
  },
  {
    number: "03",
    label: "AI & Search",
    title: "Intelligence Layer",
    description: "Vector embeddings, local neural inference, and hybrid search ranking.",
    items: [
      {
        id: "llm-apis",
        name: "LLM APIs",
        glyph: "✧",
        category: "AI & Search",
        role: "Structured function calling, agentic orchestration, and streaming tokens.",
        connectedIds: ["rag", "vector-search", "nodejs", "typescript"],
        project: { title: "Glint", slug: "glint" },
        specs: ["Structured JSON Outputs", "Prompt Optimization", "Token Streaming"],
      },
      {
        id: "rag",
        name: "RAG",
        glyph: "◈",
        category: "AI & Search",
        role: "Retrieval-Augmented Generation with semantic context injection.",
        connectedIds: ["vector-search", "bm25", "onnx", "llm-apis"],
        project: { title: "Glint", slug: "glint" },
        specs: ["Reciprocal Rank Fusion", "Context Chunking", "Grounding Prompts"],
      },
      {
        id: "vector-search",
        name: "Vector Search",
        glyph: "⚲",
        category: "AI & Search",
        role: "Cosine similarity indexing, high-dimensional embeddings, and dense retrieval.",
        connectedIds: ["onnx", "rag", "bm25"],
        project: { title: "Glint", slug: "glint" },
        specs: ["Cosine Similarity", "Dense Vectors (384-dim)", "Sub-50ms Retrieval"],
      },
      {
        id: "onnx",
        name: "ONNX",
        glyph: "⚙",
        category: "AI & Search",
        role: "Cross-platform hardware-accelerated local neural network runtime.",
        connectedIds: ["vector-search", "rag", "typescript"],
        project: { title: "Glint", slug: "glint" },
        specs: ["Local CPU/GPU Inference", "Zero-Cloud Dependency", "Quantized Models"],
      },
      {
        id: "bm25",
        name: "BM25",
        glyph: "⌕",
        category: "AI & Search",
        role: "Exact keyword matching and probabilistic term-frequency relevance ranking.",
        connectedIds: ["rag", "vector-search"],
        project: { title: "Glint", slug: "glint" },
        specs: ["Term Frequency Weighting", "Inverted Indexing", "Hybrid Search Bridge"],
      },
      {
        id: "ollama",
        name: "Ollama",
        glyph: "◎",
        category: "AI & Search",
        role: "Local LLM model serving, quantized weight execution, and offline reasoning.",
        connectedIds: ["rag", "llm-apis"],
        project: { title: "Glint", slug: "glint" },
        specs: ["Local Weight Serving", "Offline Privacy", "OpenAI Compatible API"],
      },
    ],
  },
  {
    number: "04",
    label: "Infrastructure",
    title: "Cloud & Delivery",
    description: "Containerization, automated CI/CD pipelines, and edge deployment.",
    items: [
      {
        id: "docker",
        name: "Docker",
        glyph: "⎔",
        category: "Infrastructure",
        role: "Multi-stage container builds, reproducible environments, and local staging.",
        connectedIds: ["nodejs", "cicd", "github-actions"],
        project: { title: "Glint", slug: "glint" },
        specs: ["Multi-Stage Builds", "Alpine Minification", "Layer Caching"],
      },
      {
        id: "github-actions",
        name: "GitHub Actions",
        glyph: "⟳",
        category: "Infrastructure",
        role: "Automated linting, type-checking, unit test execution, and deployment triggers.",
        connectedIds: ["cicd", "docker", "vercel"],
        project: { title: "Pitchery", slug: "pitchery" },
        specs: ["Automated Test Matrix", "Branch Protection Checks", "Artifact Generation"],
      },
      {
        id: "vercel",
        name: "Vercel",
        glyph: "▲",
        category: "Infrastructure",
        role: "Serverless edge functions, global CDN edge caching, and preview environments.",
        connectedIds: ["nextjs", "react", "github-actions"],
        project: { title: "Pitchery", slug: "pitchery" },
        specs: ["Edge Network CDN", "Instant Rollbacks", "Serverless Functions"],
      },
      {
        id: "cloud-platforms",
        name: "Cloud Platforms",
        glyph: "☁",
        category: "Infrastructure",
        role: "Managed database provisioning, object storage, and DNS configuration.",
        connectedIds: ["postgresql", "docker", "vercel"],
        project: { title: "Pitchery", slug: "pitchery" },
        specs: ["Neon Serverless Postgres", "HTTPS / SSL Automation", "Edge DNS"],
      },
      {
        id: "cicd",
        name: "CI/CD",
        glyph: "⚙",
        category: "Infrastructure",
        role: "Continuous integration pipelines with automated regression prevention.",
        connectedIds: ["github-actions", "docker", "vercel"],
        project: { title: "Pitchery", slug: "pitchery" },
        specs: ["Zero-Downtime Deployments", "Automated Smoke Tests", "Pre-Deploy Checks"],
      },
    ],
  },
];
